language: c

before_script:
    - curl -L https://www.opscode.com/chef/install.sh | sudo bash
    - gem install librarian-chef --no-rdoc --no-ri
    - librarian-chef install --verbose
    - echo "cookbook_path [ \"/home/travis/build/Kunstmaan/skylab/cookbooks\" ]" > solo.rb
    - sudo service mysql stop
    - sudo apt-get -y purge mysql*
    - sudo rm -Rf /var/lib/mysql/
    - sudo service postgresql stop
    - sudo apt-get -y purge postgresql*
    - sudo rm -Rf /etc/postgresql/
    - sudo rm -Rf /etc/postgresql-common/
    - sudo rm -Rf /var/lib/postgresql/
    - sudo chef-solo --log_level debug -c solo.rb -o "skylab::default"
    - composer install --prefer-source

script:
    - ./compile --version 0.0.0
    - php skylab.phar new test -vvv --no-interaction
    - php skylab.phar apply test symfony -vvv --no-interaction
    - php skylab.phar maintenance -vvv --no-interaction
    - php skylab.phar backup -vvv --no-interaction
    - php skylab.phar permissions test -vvv --no-interaction
    - php skylab.phar remove test --force -vvv --no-interaction
    - ./skylab new test -vvv --no-interaction
    - ./skylab apply test symfony -vvv --no-interaction
    - ./skylab maintenance -vvv --no-interaction
    - ./skylab backup -vvv --no-interaction
    - ./skylab permissions test -vvv --no-interaction
    - ./skylab remove test --force -vvv --no-interaction
    - php skylab.phar new test -vvv --no-interaction
    - php skylab.phar apply test smartcms -vvv --no-interaction
    - php skylab.phar maintenance -vvv --no-interaction
    - php skylab.phar backup -vvv --no-interaction
    - php skylab.phar permissions test -vvv --no-interaction
    - php skylab.phar remove test --force -vvv --no-interaction
    - ./skylab new test -vvv --no-interaction
    - ./skylab apply test smartcms -vvv --no-interaction
    - ./skylab maintenance -vvv --no-interaction
    - ./skylab backup -vvv --no-interaction
    - ./skylab permissions test -vvv --no-interaction
    - ./skylab remove test --force -vvv --no-interaction
    - php skylab.phar self-update --no-interaction
    - cd /tmp && curl -sS https://raw.github.com/Kunstmaan/skylab/master/installer.php | php

