language: php
sudo: false
cache:
  directories:
  - $HOME/.composer/cache/files
matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
before_install:
- mkdir out
- composer self-update
- composer global require kherge/box:2.7.3
- PATH=$PATH:/home/travis/.composer/vendor/bin/
script:
- composer install --optimize-autoloader
- box build
- sha1sum out/skylab.phar > out/skylab.version
deploy:
  - provider: releases
    api_key:
      secure: VeGS+1kHv1J6rW3iY8Klq0fYIO3r3UPwKvb8h0JszyWrjHAhNrcu06MQ7ibdJ6Lcl784TQnVUHd3BzFYBVmYSsXG3Qt72drBvBNvygobPhGpqulgZtHstA9U8T7CppM8+fJk3MFJI+re6HeCcu9UVidpKcDIb33W47CKzO02h6E=
    file: out/skylab.phar
    on:
      repo: Kunstmaan/skylab
      php: 7.0
      tags: true
  - provider: s3
    access_key_id:
      secure: OqEEWH2WyMF/5HXPnPi+nSJ7Lz3dj7lOZnh7vQ+SWOw0EW6r4NGZtQZQLw8gOyLgU9wqnBuT95ke6Bo7b1HDW3N4Ffy6ODgEO8gBQjXP0j/QOxk9H4yzX/nYirfdYM1XmhlY1IJFQ4DtoCyS4rjGy22pm0TN02XGsx2WjOrZlJQ=
    secret_access_key:
      secure: SEpKEkPfMN5avhtbD7iVRXhlmdlxx/zF1z6ZEX6BAworPEoZ/j3K5VqTPV2kpKgA965kPzx+umAcdxJiSoPA1vZngUih+ZPpn1QUbuv/CnMKntVNCTH20WHvvpMeamBGsiwnsGV1urKKkl+GIx5SQ65LAU4AhBR1rMSQE9VVzVQ=
    bucket: kunstmaan-skylab
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    local_dir: out
    on:
      repo: Kunstmaan/skylab
      php: 7.0
      branch: master
notifications:
  slack:
    secure: YPOKgHTBB/kJJCd6fsUhZxHE4TLAXWvzCGlAUT1LyTdMrIKgW2we31b24iYyNuYbb3LSTTCc1ipByh5kzjM9o+uzHvS3GbSkh8Kdn+e4b62Z+6g1TiLfFZcJi/vorPyHuUVFGhTryTBTxMwDNbQBNMxMkMxofYLfOszsBx1dOkw=
