#!/usr/bin/env php
<?php
$autoload = __DIR__.'/vendor/autoload.php';
if (!file_exists($autoload)) {
    echo "Please run `php composer.phar install` first." . PHP_EOL;
    exit(1);
}

require_once $autoload;

use Kunstmaan\Skylab\Compiler;

error_reporting(-1);
ini_set('display_errors', 1);

//v0.1-alpha

$longopts  = array(
    "version:"
);
$options = getopt('', $longopts);
if (!isset($options["version"])){
    die("\n--version is a required argument\n\n");
}
$version = $options["version"];

try {
    $compiler = new Compiler();
    $compiler->compile($version);
} catch (\Exception $e) {
    echo 'Failed to compile phar: ['.get_class($e).'] '.$e->getMessage().' at '.$e->getFile().':'.$e->getLine();
    exit(1);
}