steps:
  - ssh %deploy_server% -p %deploy_port% "sudo rm -rf %projects_path%/%deploy_project%/conf"
  - ssh %deploy_server% -p %deploy_port% "sudo ln -s %projects_path%/%deploy_project%/data/builds/%deploy_timestamp%-%buildtag%/.skylab/conf %projects_path%/%deploy_project%/conf"